version: '3'

services:
  selenium-hub:
    image: selenium/hub:3.141.59-20200409
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - acas-grid

  firefox:
    image: selenium/node-firefox:3.141.59-20200409
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - START_XVFB=true
    networks:
      - acas-grid

  chrome:
    image: selenium/node-chrome:3.141.59-20200409
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - START_XVFB=true
    networks:
      - acas-grid

  chrome-debug:
    image: selenium/node-chrome-debug:3.141.59-20200409
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - START_XVFB=true
    ports:
      - "5900:5900"
    networks:
      - acas-grid

  eb-spider:
    build: ./eb
    depends_on:
      - chrome
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - BROWSER=chrome
      - LOGGING_CONFIG_YAML=./logging.yaml
    volumes:
      - ./eb/screenshots:/code/screenshots
    networks:
      - acas-grid

networks:
  acas-grid:
